name: stack_overflow
version: '1.0'
config-version: 2

profile: rittman_analytics

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  stack_overflow:
    bronze:
      +database: "{{ env_var('BQ_PROJECT') }}"
      +schema: bronze
      +materialized: table
    silver:
      +database: "{{ env_var('BQ_PROJECT') }}"
      +schema: silver
      +materialized: view
    gold:
      +database: "{{ env_var('BQ_PROJECT') }}"
      +schema: gold
      +materialized: table

